
PROG = my_ext2fs

LAB  = LAB6

#
# 'make'		compiles everything
#
# 'make clean'	removes all object files
#
# 'make tar'	adds everything needed to recreate executable into a tar and compresses
#
# 'make submit'	uploads tar to KC's server into directory defined by LAB 
#

.PHONY : all clean tar submit depend

# Add any additional utility files here
SOURCE = main.c cmd.c \
		 util.c input.c print.c memory.c transfer.c search.c
	
DEBUG    = -g -Wall -O0
# -g 		add debugging info
# -Wall		enable most compiler warnings
# -O0		reduce compilation time and make debugging produce the expected results

###### Libraries ######
LIBS     = #-lmylib -lm

CC     = gcc
CFLAGS = $(INCLUDES) $(DEBUG)
LFLAGS = #-L../lib include libraries not in /usr/lib

###### Directories ######
CUR_DIR  = .
UTIL_DIR = util
CMD_DIR  = cmd
CMD1_DIR = cmd/level_1
CMD2_DIR = cmd/level_2
CMD3_DIR = cmd/level_3
OBJ_DIR  = obj
DISK_DIR = disk

# -Idir
# Add the directory dir to the head of the list of directories to be searched for header files. 
# This can be used to override a system header file, substituting your own version, 
# since these directories are searched before the system header file directories. 
INCLUDES = -I$(CUR_DIR)  \
		   -I$(UTIL_DIR) \
		   -I$(CMD_DIR)  \
		   -I$(CMD1_DIR) \
		   -I$(CMD2_DIR) \
		   -I$(CMD3_DIR) \

# VPATH specifies a list of directories that make should search
VPATH = $(UTIL_DIR) $(CMD_DIR) $(OBJ_DIR)

OBJECTS = $(SOURCE:.c=.o)

OBJPROG = $(addprefix $(OBJ_DIR)/, $(PROG))

# make
all : $(OBJPROG)

$(OBJECTS) : | $(OBJ_DIR)

$(OBJ_DIR) :
	@mkdir -p $@

$(OBJPROG) : $(addprefix $(OBJ_DIR)/, $(OBJECTS))
	$(CC) $(CFLAGS) $^ $(LFLAGS) $(LIBS) -o $(PROG)

$(OBJ_DIR)/%.o : %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean :
	@$(RM) -f $(PROG) $(OBJ_DIR)/*.o *~ 

tar :
	tar -zcfv $(PROG).tar.gz $(UTIL_DIR) $(CMD_DIR) *.c *.h makefile 

submit : tar
	script/upload.sh $(LAB) $(PROG).tar.gz

# The makedepend program reads each sourcefile in sequence and parses it like a C-preprocessor, 
# processing all #include, #define, #undef, #ifdef, #ifndef, #endif, #if, #elif and #else directives 
# so that it can correctly tell which #include, directives would be used in a compilation. 
# Any #include, directives can reference files having other #include directives, 
# and parsing will occur in these files as well.  
depend : 
	makedepend -- $(CFLAGS) -I/usr/include/linux/ -I/usr/lib/gcc/i686-redhat-linux/4.8.3/include/ -- $(SOURCE)

# DO NOT DELETE THIS LINE -- make depend needs it

main.o: /usr/include/stdio.h /usr/include/features.h
main.o: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
main.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
main.o: /usr/include/gnu/stubs-32.h /usr/include/linux/stddef.h
main.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
main.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
main.o: /usr/lib/gcc/i686-redhat-linux/4.8.3/include/stdarg.h
main.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
main.o: ./global.h /usr/include/linux/fcntl.h /usr/include/asm/fcntl.h
main.o: /usr/include/asm-generic/fcntl.h /usr/include/linux/types.h
main.o: /usr/include/asm/types.h /usr/include/asm-generic/types.h
main.o: /usr/include/asm-generic/int-ll64.h /usr/include/asm/bitsperlong.h
main.o: /usr/include/asm-generic/bitsperlong.h
main.o: /usr/include/linux/posix_types.h /usr/include/linux/stddef.h
main.o: /usr/include/asm/posix_types.h /usr/include/asm/posix_types_32.h
main.o: /usr/include/asm-generic/posix_types.h /usr/include/ext2fs/ext2_fs.h
main.o: /usr/include/ext2fs/ext2_types.h
main.o: /usr/include/ext2fs/ext2_types-i386.h /usr/include/libgen.h
main.o: /usr/include/linux/string.h /usr/include/sys/stat.h
main.o: /usr/include/linux/time.h /usr/include/bits/stat.h util/input.h
main.o: /usr/include/stdlib.h /usr/include/bits/waitflags.h
main.o: /usr/include/bits/waitstatus.h /usr/include/endian.h
main.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
main.o: /usr/include/bits/byteswap-16.h /usr/include/sys/types.h
main.o: /usr/include/sys/select.h /usr/include/bits/select.h
main.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
main.o: /usr/include/sys/sysmacros.h /usr/include/alloca.h
main.o: /usr/include/bits/stdlib-float.h /usr/include/ctype.h
main.o: /usr/include/xlocale.h util/print.h util/util.h
main.o: /usr/include/linux/unistd.h /usr/include/asm/unistd.h
main.o: /usr/include/asm/unistd_32.h util/transfer.h util/memory.h cmd/cmd.h
main.o: util/search.h
